---

- name: Disable all RHUI repos
  shell:
    cmd: sed -i 's|enabled=1|enabled=0|g' /etc/yum.repos.d/*rhui*.repo

- name: Add and configure RPM repositories (RHEL 8)
  template:
    src: 'templates/rhel8-disconnected.repo.j2'
    dest: '/etc/yum.repos.d/rhel8-disconnected.repo'
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int == 8

- name: Add and configure RPM repositories (RHEL 7)
  template:
    src: 'templates/rhel7-disconnected.repo.j2'
    dest: '/etc/yum.repos.d/rhel7-disconnected.repo'
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat" and ansible_distribution_version|int == 7

- name: Update all packages
  yum:
    name: "*"
    state: latest
    exclude: atomic-openshift-ansible*,openshift-ansible*
  retries: 3 # This seems to fail sometimes, so lets retry before failing everything
  until: update_all_packages.rc == 0
  register: update_all_packages
  become: true

- block:
    - name: Reboot host
      shell: sleep 30 && shutdown -r now
      async: 30
      poll: 0
      ignore_errors: true
      become: true

    - name: Wait for nodes to boot
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 30
        timeout: 300
        search_regex: OpenSSH
      delegate_to: localhost
  when: "'kernel' in update_all_packages.results"

- name: Install preferred packages
  become: true
  yum:
    name:
      - vim
      - screen
      - docker-ce
    state: present

- name: stop the docker daemon
  become: true
  systemd:
    name: docker
    state: stopped

- name: Ensure docker group exists
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    name: ec2-user
    groups: docker

- name: Start and enable the docker daemon
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

- name: Install private registry certificate
  become: true
  copy:
    src: '{{ registry_cert }}'
    dest: '/etc/pki/ca-trust/source/anchors/registry.crt'
    owner: root
    group: root
    mode: '0644'

- name: Update CA trust
  become: true
  shell:
    cmd: update-ca-trust extract

- name: Configure firewall
  include_tasks: firewall.yml

