---

- name: Create mirror base directory for images
  file:
    path: '{{ mirror_base }}/images'
    state: directory

- name: Pull image list for release {{ rancher_version }}
  get_url:
    url: 'https://github.com/rancher/rancher/releases/download/v{{ rancher_version }}/rancher-images.txt'
    dest: '{{ mirror_base }}/rancher-images.txt'

- name: Install skopeo
  become: true
  package:
    name: skopeo
    state: present

- name: Pull Core Rancher Images
  shell:
    cmd: |

        if ! test -e "{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar"
        then
          skopeo copy --authfile "{{ pull_secret }}" \
            "docker://docker.io/{{item}}" "docker-archive://{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar"

        fi

    executable: /bin/bash
  with_items:
    - "{{ lookup('file', '{{ mirror_base }}/rancher-images.txt').splitlines() }}"
  tags:
    - pull

- name: Pull Additional Rancher Images
  shell:
    cmd: |

        if ! test -e "{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar"
        then
          skopeo copy --authfile "{{ pull_secret }}" \
            "docker://{{item}}" "docker-archive://{{ mirror_base }}/images/{{ ( item | replace(':','_') | replace('/','-') | replace('.','_') ) }}.tar"

        fi

    executable: /bin/bash
  with_items:
    - '{{ additional_images }}'
  tags:
    - pull
