---

- name: Push Core Rancher Images
  shell:
    cmd: |

        if test -e "{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar"
        then
          skopeo copy --authfile "{{ pull_secret }}" \
          "docker-archive://{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar" \
          "docker://{{mirror_registry}}/{{item}}"
        fi

    executable: /bin/bash
  with_items:
    - "{{ lookup('file', '{{ mirror_base }}/rancher-images.txt').splitlines() }}"
  tags:
    - push

- name: Push Additional Rancher Images
  shell:
    cmd: |

        if test -e "{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar"
        then
          skopeo copy --authfile "{{ pull_secret }}" \
          "docker-archive://{{ mirror_base }}/images/{{ ( item | replace(':','_') | replace('/','-') | replace('.','_') ) }}.tar" \
          "docker://{{mirror_registry}}/{{item}}"
        fi

    executable: /bin/bash
  with_items:
    - '{{ additional_images }}'
  tags:
    - push
