---

- name: Push images to registry
  become: true
  shell:
    cmd: |

        if test -e "{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar"
        then
          skopeo copy --authfile "{{ pull_secret }}" \
            "docker-archive://{{ mirror_base }}/images/docker_io-{{ ( item | replace(':','_') | replace('/','-') ) }}.tar" \
            "docker://{{mirror_registry}}/{{item}}"
        fi

    executable: /bin/bash
  loop: "{{ lookup('file', '{{ mirror_base }}/rancher-images.txt').splitlines() }}"
  tags:
    - pull
