---

rancher_version: '2.4.5'
rke_version: '1.1.3'
arch: 'amd64'

mirror_base: '/tmp/rancher'

mirror_registry: 'localhost:5000'

pull_secret: '{{ ansible_env.HOME }}/.docker/config.json'

cert_manager_version: 'v0.12.0'

additional_images:
  - 'quay.io/jetstack/cert-manager-controller:{{ cert_manager_version }}'
  - 'quay.io/jetstack/cert-manager-webhook:{{ cert_manager_version }}'
  - 'quay.io/jetstack/cert-manager-cainjector:{{ cert_manager_version }}'
#  - 'quay.io/jetstack/cert-manager-acmesolver:{{ cert_manager_version }}'
